spring.application.name=leaveflow
spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-broad-voice-a1gwmtyt.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
# --- Swagger / OpenAPI enabled in all envs (including prod) ---

# Keep /v3/api-docs JSON endpoint enabled
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

# Keep Swagger UI enabled and at the standard URL
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
# ===============================
# MAIL (SMTP) - Use App Password for Gmail
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kafleashish53@gmail.com
spring.mail.password=ghpuetpdrshbtpjj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# JWT
# ===============================
jwt.secret=Y8pQZ2r6B4H9eM3xK7TnAqD5sLJcU0WfRk1oEIvSbNhXyP
jwt.expiration=86400000
